// Generated by CoffeeScript 1.8.0
var UI, Vector2, menu;

UI = require('ui');

Vector2 = require('vector2');

menu = new UI.Menu({
  sections: [
    {
      title: 'Theme',
      items: [
        {
          title: 'Nature'
        }, {
          title: 'Pop'
        }
      ]
    }
  ]
});

menu.show();
