// Generated by CoffeeScript 1.8.0
var UI, Vector2, ajax, menu;

UI = require('ui');

Vector2 = require('vector2');

ajax = require('ajax');

menu = new UI.Menu({
  sections: [
    {
      title: 'Theme',
      items: [
        {
          title: 'Nature'
        }, {
          title: 'Pop'
        }
      ]
    }
  ]
});

menu.on('select', function(e) {
  return ajax({
    url: 'https://beo.firebaseio.com/ombr/theme',
    method: 'put',
    data: e.item.title
  }, (function() {
    return menu.hide();
  }), (function() {}));
});

menu.show();
