// Generated by CoffeeScript 1.8.0
var UI, Vector2, ajax, menu;

UI = require('ui');

Vector2 = require('vector2');

ajax = require('ajax');

menu = new UI.Menu({
  sections: [
    {
      title: 'Theme',
      items: [
        {
          title: 'Zen'
        }, {
          title: 'Pop'
        }, {
          title: 'Reggae'
        }, {
          title: 'Rock'
        }, {
          title: 'Classique'
        }, {
          title: 'Rap'
        }
      ]
    }
  ]
});

menu.on('select', function(e) {
  console.log('"' + e.item.title + '"');
  return ajax({
    url: 'https://beo.firebaseio.com/ombr/theme.json',
    method: 'put',
    type: 'json',
    data: e.item.title
  }, (function(data) {
    console.log('succes');
    return menu.hide();
  }), (function(err) {
    console.log(err);
    return console.log('error');
  }));
});

menu.show();
